# Generated by Django 2.2.4 on 2019-08-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(max_length=100)),
                ('Titulo', models.CharField(max_length=200)),
                ('Preço', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Texto_Anuncio', models.CharField(max_length=1000)),
                ('Nome_do_Contato', models.CharField(max_length=50)),
                ('Telefone', models.CharField(max_length=200)),
                ('secao', models.CharField(max_length=50)),
                ('Tipo_de_Anuncio', models.CharField(max_length=1000)),
            ],
        ),
    ]
