# Generated by Django 2.2.4 on 2019-10-27 15:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('fone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name_plural': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=20, verbose_name='Logradouro')),
                ('numero', models.IntegerField(max_length=4, verbose_name='Número')),
                ('complemento', models.CharField(max_length=30, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=15, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=15, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Cep number must be entered in the format: '64000000'. Up to 10 digits allowed.", regex='^\\+?1?\\d{8,10}$')])),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='ItemTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição do Item')),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('valor', models.FloatField(verbose_name='Valor Aluguel')),
                ('cor_toalha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festa.ItemTema')),
            ],
            options={
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Festa')),
                ('horainicio', models.TimeField(verbose_name='Hora Inicio')),
                ('horatermino', models.TimeField(verbose_name='Hora Termino')),
                ('valor', models.FloatField(verbose_name='Valor Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festa.Cliente')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festa.Endereco')),
                ('tema_escolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festa.Tema')),
            ],
            options={
                'verbose_name': 'Aluguel Agendado',
                'verbose_name_plural': 'Alugueis Agendados',
                'ordering': ('-data', 'horainicio'),
            },
        ),
    ]
