# Generated by Django 2.2.5 on 2019-12-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
