# Generated by Django 2.2.4 on 2019-10-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revistaquadrinhos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='nome_mae',
            field=models.CharField(max_length=30, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='ano',
            field=models.IntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='ano',
            field=models.IntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='numero',
            field=models.IntegerField(verbose_name='Número de Edição'),
        ),
    ]
