# Generated by Django 2.2.4 on 2019-10-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Valor',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='fone_number',
            new_name='fone',
        ),
    ]
