# Generated by Django 2.2.4 on 2019-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20191027_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Ident. Turma'),
        ),
    ]
