# Generated by Django 2.2.4 on 2019-08-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField()),
                ('Qtd_Quartos', models.IntegerField()),
                ('Proprietario', models.CharField(max_length=100)),
                ('Valor_Condominio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
