# Generated by Django 2.2.4 on 2019-08-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Descrição_Produto', models.CharField(max_length=300)),
                ('Unidade_Compra', models.CharField(max_length=300)),
                ('Data_Compra', models.DateField()),
                ('Valor', models.FloatField()),
            ],
        ),
    ]
