# Generated by Django 2.2.4 on 2019-08-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='Descrição',
            field=models.CharField(max_length=100),
        ),
    ]
